select  YEAR(E.DIFFERENTIATION_DATE) YEAR,E1.max_size-E.SIZE_OF_COLONY YEAR_DEV, E.ID
from ECOLI_DATA E inner join 
(select max(SIZE_OF_COLONY) as max_size, DIFFERENTIATION_DATE from ECOLI_DATA group by DIFFERENTIATION_DATE) E1
on E.DIFFERENTIATION_DATE=E1.DIFFERENTIATION_DATE
ORDER BY E.DIFFERENTIATION_DATE, YEAR_DEV 