SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    E1.max_size - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS y,
        MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) E1
ON YEAR(E.DIFFERENTIATION_DATE) = E1.y
ORDER BY YEAR, YEAR_DEV;