select DISTINCT D.ID as ID, D.EMAIL as EMAIL, D.FIRST_NAME as FIRST_NAME, D.LAST_NAME as LAST_NAME 
fRom DEVELOPERS D,
(SELECT S.CODE CODE
FROM SKILLCODES S
WHERE S.NAME='C#' OR S.NAME='Python') SC
WHERE SC.CODE & D.SKILL_CODE>1